spring:
  application:
    name: catalog-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:uploads/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_pizzeria_gula_catalog_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC&autoReconnect=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha


server:
  port: 8081


