version: '3.9'
services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul-gula
    ports:
      - "8500:8500"   # UI web de Consul
      - "8600:8600/udp" # DNS de Consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped

  prometheus:
    container_name: prometheus-gula
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana-gula
    ports:
      - "3000:3000"